<html>
<head>
    <link href="static/style.css" rel="stylesheet" type="text/css">
    <title>Privacy Policy</title>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-51268709-1', 'pandorazipper.com');
      ga('send', 'pageview');

    </script>
</head>
<body>
    <a href="/" class='home'><< Home</a>
    <section class="info">
        <section id="how">
            <h1>How does it work?</h1>
            <p>Pandora Zipper is a PHP application that allows you to download songs that have been loaded using pandora's unofficial API.
            The program first collects 28 song urls by cycling through the 6 skip limit that pandora has. This is done through an http request that recieves
            4 songs per skip. (first 4 + 6*4 skips = 28)</p>
            <p>The application then processes the information using php reader and applies metatags in both ID3 and ilst formats through PHP Reader. Once metadata
            has been added, it is zipped and sent back to the browser for download.</p>
            <p>Want to see the above written in shitty code? <a href="https://github.com/bGrubbs/Pandora-Zipper/">Here's the git repo.</a></p>
        </section>
<<<<<<< HEAD
        <section id="legal">
            <p>According to DMCA, Digital Millennium Copyright Act, it is illegal to DISTRIBUTE, SALE, MANUFACTURE copyrighted material. It does not state that having copyright material in your possession is illegal.<p>
            <p>As long as it is played for your leisure at home, then it is fine. Pandora gets more exposure and you get more songs. win win.<p>
        </section>
=======
>>>>>>> 1f364a98cbfeeec3ffcc1b22a8df9a37f35091b2
        <section id="privacy">
            <h1>Privacy Policy</h1>
            <p>Pandora.com is the legal owner and distributor of the songs that we allow you to download for strictly personal use.</p>
            <p>We do not support or encourage the distribution or use of the music generated by this software for purposes other than personal endeavors. This includes commerce.</p>
            <p>We allow third-party companies, namely google analytics, collect certain anonymous information when you visit our web site.</p>
            <p>These companies may use non-personally identifiable information (e.g., click stream information, browser type, time and date, subject of advertisements clicked or scrolled over)
                during your visits to help us optimize and maintain our site. These companies typically use a cookie or third party web beacons to collect this information.</p>
            <p>To learn more about this behavioral advertising practice or to opt-out of this type of advertising, check out <a href="http://www.google.com/policies/technologies/ads/">how Google Analytics advertises.</a></p>
        </section>
        <section id="#DMCA">
            <h1>DMCA</h1>
            <p>If you feel that the distribution of music available here have infringed on your rights or copyrights, please send an email to <a href="mailto:flamurds@gmail.com">flamurds@gmail.com</a>
                together with your credentials and a brief reason for your claim. Our support team will respond promptly. Thank you.</p>
        </section>
    </section>
    <a href="/" class='home'><< Home</a>
</body>
</html>
